services:
  proxy:
    build: ../
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    restart: unless-stopped

  web:
    build: ./upstream
    deploy:
      replicas: 4
    restart: unless-stopped
  maintenance:
    build: ./maintenance
    restart: unless-stopped
