blank_issues_enabled: false
contact_links:
  - name: Features, Bug Reports, Questions
    url: https://github.com/basecamp/kamal-proxy/discussions/new/choose
    about: Please use the discussions area to report issues or ask questions!
